/*
 * The hymn index, carried over from the "Hymn Index" sheet of the conductor's
 * Choir Programme workbook (1317 entries, unchanged).
 *
 * Each record is  [ref, title, ability, organ, comment, slots, seasons, rounds]
 * with trailing empty fields dropped.
 *
 *   ref      "34" from the hymn book, "E 283" English, "A 12" Afrikaans
 *   ability  E Easy, P Practice, T Tricky, D Difficult, U Unknown, N New
 *   organ    Y organ accompaniment, N unaccompanied
 *   slots    points of the service the hymn suits, comma separated:
 *            bs before service, at after the text word, cu call-up,
 *            com Holy Communion, as after service, dep for the departed.
 *            A trailing "?" is the sheet's own "???" - suits it, unconfirmed.
 *   seasons  c Christmas, e Easter, t Thanksgiving
 *   rounds   the sheet's First/Second/Third practice columns, e.g. "1:6"
 */
window.HYMN_DATA = [
["1", "A glorious land awaits us", "E", "N", "", "bs,at,cu,as"],
["2", "Jesus my Saviour", "E", "N", "", "bs,at,cu"],
["3", "Rejoice, He has risen!", "U", "N", "", "bs,at,cu"],
["4", "What you receive this glorious day", "U", "N", "", "bs,at,cu"],
["5", "Lead me , Saviour , to my rest", "T", "N", "", "bs,at,cu"],
["6", "Keep me upon Thy pathway", "P", "N", "", "bs,at,cu"],
["7", "Blessed are the pure in heart", "T", "N", "", "bs,at,cu"],
["8", "Earthly joy is ever fleeting", "P", "N", "New Words", "bs,at,cu"],
["9", "As now we strive towards the goal", "T", "N", "Ending", "bs,at,cu"],
["10", "This holy temple", "P", "N", "", "bs,at"],
["11", "The Lord has cleansed me", "E", "N", "", "at,com,as"],
["12", "How lovely is Zion", "P", "Y", "", "bs,at,as"],
["13", "Blest are they", "P", "N", "", "bs,at,cu"],
["14", "Thou holy will of my dear soul", "T", "N", "", "bs,at,cu"],
["15", "My times are in Thy hands", "P", "N"],
["16", "My son, give me thine heart", "E", "N", "", "bs,at,cu"],
["17", "Behold, I stand at the door", "E", "N", "", "bs,at,cu"],
["18", "All glory to God", "P", "N", "", "as"],
["19", "Jesus through Apostles leads us", "E", "N", "", "bs,at,cu"],
["20", "Heav'nly Father send Thy blessing", "E", "N", "", "bs,at,cu"],
["21", "Blessed and Holy", "E", "Y", "", "bs,at,cu,as"],
["22", "God be with you….", "T", "N", "", "dep"],
["23", "Follow Christ in His anointed", "E", "N", "", "bs,at,cu"],
["24", "My heart and soul are joyful", "E", "N", "", "bs,at,cu,as"],
["25", "A fount of love", "T", "N", "Ending Changed", "bs,at,cu,as"],
["26", "Rejoice! Rejoice! Sing praises", "E", "N", "", "as"],
["27", "Praise, Honour, Thanks", "U", "N", "", "as", "t"],
["28", "They that sow in tears", "E", "N", "", "bs,at"],
["29", "Glory praise and honour", "E", "N", "", "as", "t"],
["30", "Holy is the Lord of hosts", "E", "N", "", "bs,at"],
["31", "All thanks and praises", "E", "N", "", "as", "t"],
["32", "Almighty God", "E", "N", "", "as"],
["33", "Our hearts sing with joy", "E", "N", "", "as"],
["34", "Lord take whate'er I have", "E", "N", "", "bs,at,cu", "", "1:6"],
["35", "Hear us, blessed Saviour", "T", "Y", "", "bs,at"],
["36", "All life poureth forth", "E", "N", "", "bs,at,cu,as"],
["37", "Take my heart", "E", "N", "", "bs,at,cu"],
["38", "Today, God's grace", "E", "N", "", "bs,at,cu"],
["39", "At the living altar", "E", "N", "", "bs,at,cu"],
["40", "We shall remain united", "E", "N", "", "bs,at,cu"],
["41", "This is the day", "T", "N", "", "bs,as"],
["42", "The living word", "E", "N", "", "bs,at,cu"],
["43", "Thou hast cleansed me", "T", "N", "", "com"],
["44", "Strengthen us this day", "E", "N", "", "bs,at"],
["45", "Hosanna we sing", "U", "Y", "", "as", "t"],
["46", "Home, sweet home", "E", "N", "Alto Solo", "bs,at,cu,as"],
["47", "We raise a joyful chorus", "E", "N", "Voices Split", "bs,at,as"],
["48", "Thanks and praises", "U", "N", "", "as", "t"],
["49", "Praise, glory, honour", "E", "N", "", "as", "t"],
["50", "Pour out thy blessing", "E", "N", "", "bs,at"],
["51", "At the cross, from Christ…", "E", "N", "", "bs,at,com"],
["52", "God is my song", "P", "N", "", "bs,at,cu,as"],
["53", "Tho' your sins be as scarlet", "E", "N", "", "bs,at,cu"],
["54", "Joyfully singing", "E", "N", "", "as"],
["55", "Lord I dearly love…", "T", "N", "", "bs,at"],
["56", "Glory be unto God", "E", "N", "", "as"],
["57", "Who is he that's waiting", "E", "N", "", "bs,at,cu"],
["58", "Rise now and shine", "T", "N", "", "as"],
["59", "Father of our fathers", "E", "N", "", "bs,at,as"],
["60", "Lord, what a blessing", "E", "N", "", "bs,at,cu,com"],
["61", "A mighty tree of life", "P", "N", "Changed", "bs,at,cu"],
["62", "We thank Thee, dear God", "T", "N", "", "as", "t"],
["63", "How lovely is Zion", "P", "N", "", "as"],
["64", "Be thou faithful unto death", "T", "N", "", "bs,at"],
["65", "Comfort My own", "T", "N", "", "bs,at"],
["66", "Honour to God in the highest", "P", "N", "", "bs,as"],
["67", "The Lord is my Shepherd", "U", "N", "", "bs,at"],
["68", "We praise Thee, Master…", "U", "N", "", "as", "t"],
["69", "Thoroughly wash me", "E", "N", "", "bs,at"],
["70", "O Lord of hosts", "P", "N", "Need Tenors And Strong Bass", "bs,at"],
["71", "Hark! The morning bells", "E", "N", "", "bs,at"],
["72", "Cast thy burden on the Lord", "E", "Y", "Duette", "bs,at"],
["73", "Tis Thee who chose me, Father", "U", "N", "", "bs,at"],
["74", "Give me to drink, Lord", "E", "N", "", "bs,at,cu"],
["75", "Holy, holy, holy", "E", "N", "", "bs,at,cu"],
["76", "To be with Thee, O loving Lord", "E", "N", "", "bs,at,cu"],
["77", "Lord, Lord, we thank Thee now", "E", "N", "", "as"],
["78", "Where'er thou goest", "E", "N", "", "bs,at"],
["79", "Jesus , loving Saviour", "T", "N", "", "bs,at"],
["80", "Precious", "P", "N", "", "bs"],
["81", "When the Lord turns again", "T", "N", "", "bs,at"],
["82", "Silent, O be silent", "E", "N", "", "bs,at,cu"],
["83", "I'm but a stranger here", "P", "Y", "", "bs"],
["84", "Behold, for quickly I shall come", "U", "N", "", "bs,at"],
["85", "Lord, Lord come soon", "E", "N", "", "bs,at,cu,as"],
["86", "Everything that hath breath", "P", "N", "", "as", "t"],
["87", "He, in whose heart peace abideth", "P", "N", "Changed", "bs,at,cu"],
["88", "Come unto Me", "E", "N", "", "bs,at,cu", "", "1:8"],
["89", "Delight thyself in the Lord", "U", "N", "", "bs"],
["90", "This glorious Sunday morning", "T", "N", "", "bs"],
["91", "From my soul I sing praises", "E", "N", "", "as", "t"],
["92", "Saviour, keep us ever near Thee", "E", "N", "", "bs,at,cu"],
["93", "Awake", "T", "N", "", "bs,at,as"],
["94", "Give me Thy heart", "E", "N", "", "bs,at,cu"],
["95", "Take my heart and make it Thine Lord", "T", "N", "", "bs,at,cu"],
["96", "And then at last", "T", "N", "", "as"],
["97", "O Saviour, Lord and Master", "E", "N", "", "bs,at,cu,com"],
["98", "Lord, Thou hast now heard", "P", "Y", "", "bs,at"],
["99", "Hallelujah! Jesus leads me", "E", "N", "", "bs,at,cu"],
["100", "Love, to Thee myself I give", "E", "N", "Supp Sollo", "bs,at,cu,com"],
["101", "Jubilate", "P", "Y", "New with Organ Acc", "bs,at,as"],
["102", "Hands always praying", "P", "N", "", "bs,at"],
["103", "Lead me gently home, Father", "P", "Y", "", "bs,at"],
["104", "Thou art my Father", "T", "N", "", "bs,at"],
["105", "Peaceful and calm is my soul", "E", "N", "", "bs,at,cu"],
["106", "Lord, make me strong", "E", "N", "Bass", "bs,at,cu"],
["107", "Glory, glory to God in the highest", "E", "N", "", "as"],
["108", "Ascend my song", "P", "N", "", "bs,at,as"],
["109", "Wholly Thine am I my Saviour", "E", "N", "", "bs,at,cu"],
["110", "Commit thy way unto the Lord", "P", "N", "", "bs,at"],
["111", "Like bells of heaven ringing", "T", "N", "", "bs,at"],
["112", "O man, take counsel and forgive", "T", "N", "", "bs,at,cu"],
["113", "We stand today before Thee Lord", "E", "N", "", "bs,at,cu"],
["114", "Thou gravest once a promise", "T", "Y", "", "bs,at,cu"],
["115", "Eternal Father, true and kind", "E", "N", "", "bs,at,cu"],
["116", "Lord, we are waiting", "E", "N", "", "bs,at,cu"],
["117", "God shall wipe away all tears", "P", "N", "", "bs,at"],
["118", "Father, take me by the hand", "E", "N", "", "bs,at,cu"],
["119", "The Lord has done great things", "T", "N", "", "as", "t"],
["120", "Hearken", "P", "N", "", "bs,at"],
["121", "Make me purer", "E", "N", "", "bs,at,cu"],
["122", "Father, we come to thee", "E", "N", "", "bs,at,cu"],
["123", "See Bethesda's healing water", "E", "N", "", "bs,at,cu"],
["124", "Our life is like a summer's day", "T", "N", "", "bs,at,cu,dep"],
["125", "Lord Jesus, my solace and rest", "E", "N", "", "bs,at,cu"],
["126", "I will not let Thee go", "E", "N", "", "bs,at,cu"],
["127", "To Jesus my life I have given", "E", "N", "", "bs,at,cu"],
["128", "Today, on your heart's acre", "E", "N", "", "bs,at,cu"],
["129", "God to us is strength and power", "E", "N", "", "bs,at,cu,as"],
["130", "Lord, make me worthy", "E", "N", "", "bs,at,cu"],
["131", "God ever true abides", "T", "N", "", "bs,at,cu"],
["132", "The Lord shall preserve thee", "P", "N", "", "bs,at,cu"],
["133", "How great and mighty", "T", "N", "", "bs,at,as"],
["134", "Holy is God's house", "P", "Y", "", "bs,at"],
["135", "The Lord comes soon", "U", "N", "", "bs,at,cu"],
["136", "O blessed are they", "P", "N", "", "bs,at"],
["137", "Behold, what manner of love", "T", "N", "", "bs,at"],
["138", "The Lord God reigneth", "P", "Y", "", "bs,as"],
["139", "Hosanna, blessed is He", "E", "N", "", "bs,at,cu,as"],
["140", "Come to lifes pure fountain", "T", "N", "", "bs,at,cu"],
["141", "We are on our pilgrims journey", "E", "N", "", "bs,at,cu"],
["142", "Labour in the work of God", "E", "N", "", "bs,at,cu"],
["143", "Who are these in white array", "P", "N", "", "bs,at"],
["144", "The day of Thy return", "P", "Y", "", "bs,at"],
["145", "The yoke of sin is broken", "E", "N", "", "com"],
["146", "I need Thee every hour", "T", "Y", "", "bs,at"],
["147", "Lead us, heavenly Father", "T", "Y", "", "bs,at"],
["148", "Come ye disconsolate", "P", "Y", "", "bs,at,dep"],
["149", "Hear thou my prayer", "P", "N", "", "bs,at"],
["150", "How lovely upon the mountains", "T", "N", "", "bs,at"],
["151", "Heavenly peace", "T", "N", "", "bs,at,cu"],
["152", "Thy word is a lamp", "T", "Y", "", "bs,at"],
["153", "I wait for the Lord", "P", "Y", "", "bs,at"],
["154", "In God is our trust", "T", "Y", "", "as", "t"],
["155", "Rest in the Lord", "P", "Y", "", "bs"],
["156", "I will lift up mine eyes", "P", "N", "", "bs,as"],
["157", "Loving Saviour, let Thy mercy", "T", "N", "", "bs,at"],
["158", "God's own beloved", "E", "N", "", "bs,at,cu,as"],
["159", "The Lord is my Shepherd", "E", "N", "", "bs,at,cu"],
["160", "I kneel in quiet and wonder", "E", "N", "", "bs,at,cu,as"],
["161", "Humbly, Lord, I bow before Thee", "T", "N", "", "bs,at,cu"],
["162", "Thanks be to Thee", "P", "Y", "", "as"],
["163", "We worship the Lord", "E", "N", "", "bs,at,cu"],
["164", "This is the day", "P", "Y", "", "bs,as"],
["165", "The Lord is my light", "E", "N", "", "bs,at,as"],
["166", "God is love", "P", "Y", "", "bs,at"],
["167", "Behold, how good and joyful", "P", "Y", "", "bs,as"],
["168", "Thou art the lamb of God", "E", "N", "", "bs,at,cu"],
["169", "Come to me", "T", "N", "", "bs,at,cu"],
["170", "The Lord has helped us", "P", "N", "", "bs,at"],
["171", "Take thy shoes off", "P", "N", "", "bs,at"],
["172", "I'll sing Thy praises", "U", "N", "", "bs,as", "t"],
["173", "God is loving", "T", "N", "", "bs,at"],
["174", "The fruit of their labours", "U", "N", "", "bs?"],
["175", "How shall I praise", "T", "N", "", "bs,at,cu,as", "t"],
["176", "Lord, in Thee", "U", "N", "", "bs"],
["177", "I dearly love thy house", "E", "N", "", "bs,at,cu"],
["178", "Lord, if I share in thy mercy", "P", "N", "", "bs,at,cu"],
["179", "Cast thy burden upon the Lord", "P", "N", "", "bs,at,cu"],
["180", "Thy goodness, Lord, extendeth far", "U", "Y", "", "bs,as"],
["181", "We find our joy in Thee", "U", "N", "", "bs?,as", "t"],
["182", "Lord Jesus, fill this day with love", "P", "N", "", "bs?", "t"],
["183", "Jesus, my hearts treasure", "U", "N", "", "bs,at"],
["184", "How joyful shall it be", "U", "N", "", "bs?"],
["185", "There shines a bright light", "P", "Y", "", "bs,at"],
["186", "Who dwells in the secret place", "P", "N", "", "bs,at"],
["187", "A mountain is our faith", "D", "Y", "", "bs?", "t"],
["188", "Where to shall I be going", "P", "Y", "", "bs,at"],
["189", "They that wait upon the Lord", "U", "Y", "", "bs?"],
["190", "Jesus, take our hand and lead us", "P", "N", "", "bs?"],
["191", "Fear of God man's soul ennobles", "P", "N", "", "bs,at"],
["192", "Come, Lord, O bridegroom, come", "T", "N", "", "bs,at"],
["193", "To God be wholly dedicated", "E", "N", "", "bs,at,cu"],
["194", "He comes, the Hero strong", "E", "Y", "", "bs,at,as"],
["195", "This time of grace", "U", "N", "", "bs,at"],
["196", "Along this earthly valley", "P", "N", "", "bs,at,cu"],
["197", "Of compassion and salvation", "E", "N", "", "bs,at,cu"],
["198", "Peace amidst our earthly fears", "E", "N", "", "bs,at,cu"],
["199", "O come to God's altar", "P", "N", "", "bs?"],
["200", "Children of God, be working", "U", "N", "", "bs?"],
["201", "Give me more, Lord, of Thy Nature", "E", "N", "", "bs,at,cu"],
["202", "Let your light so shine", "D", "N", "", "bs?"],
["203", "New heavens and new earth", "U", "Y", "", "bs"],
["204", "We gather together", "P", "Y", "", "bs,at"],
["205", "How glad I am, how well for me", "E", "N", "", "com"],
["206", "Saviour, lead me lest I stray", "E", "N", "", "bs,at,cu"],
["207", "In thee, O Lord", "T", "N", "", "bs,at,as"],
["208", "Soon comes the day", "T", "N", "", "bs,at,as"],
["209", "When He cometh", "P", "Y", "", "as"],
["210", "No victory without any battle", "E", "N", "", "bs,at,cu"],
["211", "May our God grant you His blessing", "U", "N", "", "bs?"],
["212", "Homeward, in peace, go", "U", "N", "", "bs?"],
["213", "O fashion me, my Master", "E", "N", "", "bs,at,cu"],
["214", "The Lord bless thee", "T", "N", "", "bs,at,cu"],
["215", "The time grows ever shorter", "E", "N", "", "bs,at,cu"],
["216", "There where ninety nine", "E", "N", "Tenor Solo", "bs,at,cu"],
["217", "Thank ye the Lord", "T", "N", "", "bs,as", "t"],
["218", "While shepherds watched their flocks", "P", "N", "", "bs,at"],
["219", "This is the day of God", "P", "N", "", "bs,as"],
["220", "The heavens are praising", "P", "Y", "", "bs,as"],
["221", "Lord, Thy grace life brings", "U", "N", "", "bs?"],
["222", "Youth in Christ, bring thanks", "U", "N", "", "bs?"],
["223", "Praise, honour, thanks to God", "U", "Y", "", "bs?", "t"],
["224", "God's call I heard", "U", "N", "", "bs?"],
["225", "Hallelujah", "P", "Y", "New with Organ Acc", "as"],
["226", "Blessed are they", "P", "Y", "", "bs,as"],
["227", "Teach us love , O chief Apostle", "E", "N", "", "bs,at,cu"],
["228", "As the heart panteth", "U", "N", "", "bs?"],
["229", "Fashion me, dear Lord and Saviour", "U", "N", "", "bs?"],
["230", "What does my soul joy afford?", "E", "N", "", "bs,at,cu"],
["231", "When courage you are needing", "U", "N", "", "bs?"],
["232", "Here is the patience of the saints", "D", "Y", "", "bs,as"],
["233", "Father, our Father", "P", "N", "", "bs?"],
["234", "Who shall separate us", "P", "N", "", "bs"],
["235", "How fleeting is man's time", "U", "N", "", "bs?"],
["236", "Our Father, our Adviser", "U", "N", "", "bs?"],
["237", "How holy is this place", "D", "N", "", "bs?"],
["238", "Gird on your Armour", "P", "N", "", "bs"],
["239", "O how shall I receive Thee", "T", "N", "", "bs,at,cu"],
["240", "All who seek happiness", "P", "N", "", "bs?", "t"],
["241", "Reflecting on thy grace and goodness", "T", "N", "", "bs,at"],
["242", "How wonderful the name of Jesus", "P", "N", "", "bs?"],
["243", "Unto the Fathers name", "P", "Y", "", "bs,as"],
["244", "I will fill this house with glory", "P", "Y", "", "bs,at,as"],
["245", "Our longing hearts have been prepared", "P", "Y", "", "bs,at"],
["246", "Here's my soul", "P", "Y", "", "bs?"],
["247", "O Zion, sweet home of the blessed", "P", "N", "", "bs,at"],
["248", "The bridal souls await Thee now", "P", "N", "", "bs,at,cu"],
["249", "The Lord shall come", "P", "N", "", "bs?"],
["250", "How sweet are Thy words", "P", "N", "", "bs?"],
["251", "Lord, grant me mercy", "E", "N", "", "bs,at"],
["252", "I bow down at life's purest fountain", "T", "N", "", "bs,at,cu"],
["253", "Thou gravest me, Lord, life", "U", "Y", "", "bs?"],
["254", "Watch and pray", "U", "N", "", "bs?"],
["255", "I'm guided by Thy counsel", "T", "N", "", "bs,at"],
["256", "Lord God, in power and glory", "P", "Y", "", "as"],
["257", "I was glad", "P", "Y", "", "bs"],
["258", "Redeem the time", "P", "Y", "", "bs,at"],
["259", "Lord, I trust in Thy decision", "U", "N", "", "bs,at,cu"],
["260", "Lord, whom I deep in my heart carry", "T", "N", "", "bs,at,cu"],
["261", "O anxious worries, now depart", "U", "N", "", "bs?"],
["262", "In God's own house", "U", "N", "", "bs?"],
["263", "Lord, should my earthly need", "U", "N", "", "bs?"],
["264", "Be consoled, ye redeemed", "P", "Y", "", "bs?", "t"],
["265", "Lord Jesus, I in thee live", "P", "N", "", "bs?"],
["266", "Take my hand and lead me", "U", "N", "", "bs?"],
["267", "Come, let us unto God", "P", "N", "", "bs,at,as"],
["268", "Word of life , o gift from heaven", "E", "N", "", "bs,at,cu"],
["269", "Father, hear our pray'rs unceasing", "U", "N", "", "bs,at"],
["270", "My soul truly waits on the Lord", "P", "N", "", "bs,at"],
["271", "O taste and see", "P", "N", "", "bs,at,cu,as", "t"],
["272", "Once I read", "P", "Y", "Eens verneem ek Solo", "bs,at"],
["273", "Oft in life confusion governs", "U", "N", "", "bs"],
["274", "The goal draws nearer", "U", "N", "", "bs?", "t"],
["275", "When we walk with the Lord", "P", "N", "Full Choir", "bs,at"],
["276", "Thou leadest to grace", "P", "Y", "", "bs?"],
["277", "O faithful God and Father", "U", "N", "", "bs?"],
["278", "In Godly love abiding", "U", "N", "", "bs?"],
["279", "I am the bread of life", "P", "N", "", "bs,at"],
["280", "I will magnify Thee", "P", "Y", "", "bs?", "t"],
["281", "My peaceful heart breathes Amen", "P", "N", "New Words", "cu"],
["282", "My God and Father", "P", "N", "", "bs,at,cu"],
["283", "Our Father", "P", "N", "", "bs?"],
["284", "Lord as once Thy servant stood", "E", "N", "", "bs,at,cu"],
["285", "Create in me a clean heart", "U", "N", "", "bs?"],
["286", "Redemption for my soul", "E", "N", "", "bs,at,cu"],
["287", "Welcome! God's dear children", "P", "N", "", "bs?"],
["288", "Wait thou only on the Lord", "P", "N", "", "bs,at"],
["289", "Flow on, O river of love", "P", "N", "", "bs?"],
["290", "As long as this our earth", "P", "N", "", "bs?"],
["291", "If any man keeps My saying", "P", "N", "", "bs,at,cu"],
["292", "Where the trees of life ever blossom", "E", "N", "Alto Solo", "bs,at,cu"],
["293", "Who overcometh", "E", "N", "", "bs,at,cu"],
["294", "Holy Spirit, fount of blessing", "P", "N", "", "as"],
["295", "Thanks and praise", "U", "Y", "", "bs?", "t"],
["296", "The Lord is my Shepherd", "P", "N", "", "bs?"],
["297", "Great is the Lord", "T", "N", "", "as", "t"],
["298", "Lord God, Creator", "P", "N", "", "bs,at"],
["299", "Father of love", "P", "N", "", "bs,at"],
["300", "Thee, God, we bring praise", "T", "Y", "", "as", "t"],
["301", "When peace with the Father", "P", "N", "", "bs?"],
["302", "My sheep hear My voice", "P", "N", "", "bs,at"],
["303", "Grace be unto you", "P", "N", "", "bs,at,as"],
["304", "All honour, Lord, to thee", "U", "N", "", "bs?"],
["305", "In the service of the Lord", "T", "N", "", "bs,at,cu"],
["306", "Lift up your heads", "P", "Y", "", "as", "t"],
["307", "Father, whate'er of earthly bliss", "U", "Y", "", "bs,at"],
["308", "Only yet a few more moments", "P", "N", "", "bs?"],
["309", "O fount of grace, Lord Jesus Christ", "P", "N", "Alto Solo", "bs?"],
["310", "God so loved the world", "U", "N", "", "bs?"],
["311", "Patient, soul, be patient", "P", "N", "", "bs?"],
["312", "Almighty God, how wondrous", "P", "Y", "", "as"],
["313", "What lies deep within my heart", "E", "N", "", "bs,at,cu"],
["314", "O Thou, my hope", "E", "N", "", "bs,at,cu"],
["315", "Blessed words of hope", "T", "N", "", "dep"],
["316", "We praise Thee, O Lord", "E", "N", "", "as", "t", "1:6"],
["317", "Ah, could I now already be clad", "P", "N", "", "bs,at,cu"],
["318", "Upon the sure foundation", "P", "N", "", "bs,at,cu"],
["319", "The quite bells are ringing", "P", "N", "", "bs?"],
["320", "As pants the heart", "P", "Y", "", "bs,at,cu"],
["321", "Be still, my heart", "U", "N"],
["322", "Soul, be silent", "U", "N"],
["323", "Lord, here in Thy presence", "U", "N"],
["324", "Teach us, O Lord, Thy holy will", "U", "N"],
["325", "Just as You are", "E", "N"],
["326", "Lord, my time is in Thy hands", "U", "N"],
["327", "Lord, to Thee will I be turning", "U", "N"],
["328", "Keep courage still", "U", "N"],
["329", "Seek now the last soul", "U", "N"],
["330", "Mighty the showers of blessing", "E", "N"],
["331", "Trust in the Lord", "U", "N"],
["332", "They that trust in the Lord", "U", "N"],
["333", "Unknown the morrow", "U", "N"],
["334", "O Shepherds, so tenderly leading", "U", "Y"],
["335", "Make no plans without the Lord", "E", "N"],
["336", "There stand yet a rock", "P", "N"],
["337", "Almighty word", "U", "N"],
["338", "Jesus, Thou my souls true friend", "P", "N", "Full Choir"],
["339", "Seek ye first", "U", "N"],
["340", "Seek ye the Lord", "U", "Y"],
["341", "In this hour we pledge devotion", "U", "N"],
["342", "I have set watchmen", "U", "N"],
["343", "I know a jewel", "U", "N"],
["344", "The Lord has chosen Zion", "P", "N", "Full Choir"],
["345", "Lord, Thou art mine", "U", "N"],
["346", "O light of love divine", "U", "N"],
["347", "Dear Lord and Saviour of man kind", "P", "Y", "Supp Fall in"],
["348", "For the mountains shall depart", "U", "N"],
["349", "Sweetest joy, the gift of heaven", "U", "N"],
["350", "Lord Jesus, come", "U", "N"],
["351", "Come and redeem us", "P", "N"],
["352", "Here on the earth so full of sorrow", "P", "N"],
["353", "Onward and upward", "P", "N", "Full Choir"],
["354", "See the reapers as they labour", "U", "N"],
["355", "We're living in the final hour", "U", "N"],
["356", "Ever holiness perceiving", "U", "N"],
["357", "Continue in My love", "U", "N"],
["358", "O Love, that will not let me go", "U", "N"],
["359", "God is loving", "U", "Y"],
["360", "Since from heaven Thou art sent", "U", "N"],
["361", "Come to the fount of life", "E", "N"],
["362", "A streamlet is flowing", "U", "N"],
["363", "The Lord bless thee", "U", "N"],
["364", "May Father's call", "U", "N"],
["365", "Let your conversation become of Christ", "U", "N"],
["366", "Lord, I have loved the habitation", "U", "Y"],
["367", "Thy sacred place", "U", "Y"],
["368", "O Father Almighty", "U", "Y"],
["369", "O sing praises", "U", "Y"],
["370", "Lift up your heads", "P", "Y", "Supp Solo"],
["371", "Sing to the Lord", "U", "Y"],
["372", "Thou, Lord, alone", "U", "N"],
["373", "Praise ye the Lord, all ye nations", "U", "Y"],
["374", "I will sing of the mercies", "P", "N", "on cd somewhere"],
["375", "Angels, from the realms of glory", "P", "N", "Christmas"],
["376", "Glory to God", "U", "Y"],
["377", "O that I had a thousand voices", "P", "N"],
["378", "O praise and be joyful", "U", "N"],
["379", "O give thanks unto the Lord", "U", "Y"],
["380", "Thy goodness, Lord, extendeth far", "U", "N"],
["381", "Praise, my soul, the King of heaven", "U", "N"],
["382", "Sing unto God", "U", "Y"],
["383", "We praise Thee, Lord", "U", "Y"],
["384", "We praise Thee, Lord", "U", "N"],
["385", "Praise ye the Lord", "P", "N"],
["386", "How excellent", "U", "Y"],
["387", "All hail the pow'r of Jesus' Name", "E", "N"],
["388", "God's faithful children's earnest pleading", "U", "N"],
["389", "I know a realm where Jesus dwells", "P", "N", "Arranged"],
["390", "Bells guiding homeward", "P", "N"],
["391", "I'm but a guest and stranger", "U", "N"],
["392", "For my homeland, glorious homeland", "P", "Y"],
["393", "The Lord of the harvest beckons", "P", "N"],
["394", "There is a land", "U", "N"],
["395", "Therefore the redeemed of the Lord", "P", "Y"],
["396", "No night there", "E", "N"],
["397", "Come now, O soul", "U", "N"],
["398", "Holy Ghost, O loving Spirit", "U", "N"],
["399", "Come, Spirit, come", "U", "N"],
["400", "Breathe on me, breath of God", "P", "N"],
["401", "How can I forget my Lord?", "E", "N"],
["402", "Saviour, Thy dying love", "P", "Y"],
["403", "I am the way", "P", "N"],
["404", "This joyful Eastertide", "U", "N"],
["405", "Crown him with many crowns", "U", "N"],
["406", "May God bless you", "U", "N"],
["407", "We share your joy this special day", "U", "N"],
["408", "For He shall give His angels", "U", "N"],
["409", "The Lord shall preserve thee", "U", "N"],
["410", "Silent Night", "P", "N", "Christmas", "", "c"],
["411", "Beautiful Saviour", "P", "N", "Christmas", "", "c"],
["412", "It came upon the midnight clear", "P", "N", "Christmas", "", "c"],
["413", "A branch so fair has blossomed", "P", "N", "Christmas", "", "c"],
["414", "O Bethlehem, the lowly", "P", "N", "Christmas", "", "c"],
["415", "Shepherds, rejoice", "P", "N", "Christmas", "", "c"],
["416", "O little town of Bethlehem", "P", "N", "Christmas", "", "c"],
["417", "All my heart this day rejoices", "P", "Y", "Christmas", "", "c"],
["418", "Once again a year has ended", "U", "N"],
["419", "Another year in faith I've striven", "U", "N"],
["420", "Thou crownest the year with Thy goodness", "U", "N"],
["421", "Happy Birthday", "E", "N"],
["422", "Amen", "E", "N"],
["E 1", "Adoration", "U"],
["E 2", "All creatures of our God and King", "U"],
["E 3", "All things bright and beautiful", "E", "", "Children"],
["E 4", "As water to the thirsty", "P"],
["E 5", "Be still, for the presence of the Lord", "E"],
["E 6", "Come, Thou Almighty King", "U"],
["E 7", "Father God", "U"],
["E 8", "Glorify Thy Name", "U"],
["E 9", "God is in our presence", "E"],
["E 10", "God of mercy, God of grace"],
["E 11", "God, the All-powerful", "", "", "", "com"],
["E 12", "Hallelujah! Fairest morning", "E"],
["E 13", "He is exalted"],
["E 14", "Holy, holy, holy", "E"],
["E 15", "How great Thou art", "E"],
["E 16", "How lovely on the Sabbath day", "E"],
["E 17", "How shall I sing that majesty"],
["E 18", "I sing the mighty power of God"],
["E 19", "I worship You, almighty God"],
["E 20", "Joyful, joyful we adore Thee", "E"],
["E 21", "O God beyond all praising"],
["E 22", "O God, our help in ages past"],
["E 23", "O sanctified Sunday", "E"],
["E 24", "Open our eyes", "E"],
["E 25", "Surely the presence"],
["E 26", "This is the glorious day"],
["E 27", "We gather together", "E"],
["E 28", "We love the place, O God"],
["E 29", "Worthy of worship", "E"],
["E 30", "All hail the power of Jesus' name", "E"],
["E 31", "All hail the power of Jesus' name", "E", "", "slow version"],
["E 32", "All lands to God"],
["E 33", "All people that on earth do dwell"],
["E 34", "Come, Christians, join to sing"],
["E 35", "Come, you thankful people, come"],
["E 36", "For the beauty of the earth"],
["E 37", "For the fruits of all creation"],
["E 38", "Give thanks"],
["E 39", "Give to our God immortal praise"],
["E 40", "Great is Thy faithfulness", "E"],
["E 41", "How great is God's almighty kindness", "E"],
["E 42", "I sing praises", "E"],
["E 43", "Immortal, invisible, God only wise", "E"],
["E 44", "Let all things now living"],
["E 45", "Let us sing with joyful voices", "E"],
["E 46", "Lord, how can I ever praise You"],
["E 47", "Majesty", "E"],
["E 48", "May Jesus Christ be praised"],
["E 49", "Mighty God, we praise Thy name", "E"],
["E 50", "Mighty the showers of blessing", "E", "", "", "com"],
["E 51", "My heart overflows", "", "", "", "com"],
["E 52", "Now thank we all our God", "E"],
["E 53", "O for a thousand tongues to sing", "", "", "", "com"],
["E 54", "O that I had a thousand voices", "E"],
["E 55", "O worship the King"],
["E 56", "Praise our God with joyful singing"],
["E 57", "Praise the Lord who reigns above"],
["E 58", "Praise thou the Lord", "E"],
["E 59", "Praise thou the Lord, O my soul"],
["E 60", "Praise, my soul, the King of heaven", "", "", "", "com"],
["E 61", "Should I not to God be singing"],
["E 62", "Thank ye the Lord", "E"],
["E 63", "Thanks be to God", "E"],
["E 64", "The day Thou gavest"],
["E 65", "Thus far the Lord God has me brought"],
["E 66", "To God be the glory", "E", "", "", "com"],
["E 67", "To God be the glory", "", "", "", "com"],
["E 68", "We bring thanks to Jesus"],
["E 69", "We plough the fields, and scatter"],
["E 70", "We praise Thee, Lord", "E", "", "", "com"],
["E 71", "Ah, but one wish", "E"],
["E 72", "Am I ready", "E", "", "", "com"],
["E 73", "Ask ye what great things I know", "E"],
["E 74", "At the feet of Jesus", "E"],
["E 75", "Blessed assurance, Jesus is mine", "E", "", "", "com"],
["E 76", "Bridegroom, You are mine"],
["E 77", "Christ living in me", "E"],
["E 78", "Come, follow Me"],
["E 79", "Dare to a Daniel", "P"],
["E 80", "Glorious things of Thee are spoken"],
["E 81", "Heav'nward still our pathway tends"],
["E 82", "I am Jesus' little friend"],
["E 83", "I am the Way", "E"],
["E 84", "I am Thine, O Lord", "E", "", "", "com"],
["E 85", "I do not ask for earthly store", "E"],
["E 86", "I love to tell the story", "E"],
["E 87", "I surrender all", "", "", "", "com"],
["E 88", "I surrender all", "E", "", "", "com"],
["E 89", "I want to be like Jesus", "E", "", "", "com"],
["E 90", "I will never cease to love You"],
["E 91", "I will sing of my Redeemer", "E", "", "", "com"],
["E 92", "In Christ alone"],
["E 93", "Jesus calls us"],
["E 94", "Jesus,Thou art our salvation"],
["E 95", "Keep me upon Thy pathway", "E"],
["E 96", "Lord, my Saviour and my Shepherd"],
["E 97", "Lord, You are the Light"],
["E 98", "May the mind of Christ, my Saviour"],
["E 99", "More holiness give me"],
["E 100", "O Thou great God"],
["E 101", "O Jesus, I have promised"],
["E 102", "O, how I love Jesus", "", "", "", "com"],
["E 103", "One heart and soul"],
["E 104", "Praise, I will praise You, Lord"],
["E 105", "Soul, arise! I must be telling", "E", "", "", "com"],
["E 106", "Take my life and let it be"],
["E 107", "Take my life and let it be", "N"],
["E 108", "The Fathers house is our delight", "E"],
["E 109", "The Lord is King"],
["E 110", "Thee will I love"],
["E 111", "There's a glorious banner"],
["E 112", "This be ever my confesion", "E", "", "", "com"],
["E 113", "Up, arise, O godly witness"],
["E 114", "We cannot but be speaking"],
["E 115", "We praise Thee, Lord, Thou Lion", "E"],
["E 116", "Windows open toward Jerusalem", "E"],
["E 117", "Word of life, Thou purest fountain", "E"],
["E 118", "Your wisdom, Lord, awake in me", "E"],
["E 119", "Your word, O Lord, is gentle dew"],
["E 120", "Arise and let us hasten", "E"],
["E 121", "Awake"],
["E 122", "Brighten every corner"],
["E 123", "Brightly beams our Father's mercy", "E"],
["E 124", "Bringing in the sheaves", "E"],
["E 125", "Forth in Thy name, O Lord"],
["E 126", "Give me courage, Lord"],
["E 127", "Give me joy in my heart", "E", "", "Children"],
["E 128", "Give of your best to the master", "E"],
["E 129", "God of grace and God of glory", "E"],
["E 130", "God wants in His vineyard", "E"],
["E 131", "Have you heard the Master calling"],
["E 132", "Hear the watchmen in Zion", "E"],
["E 133", "Here I am, Lord"],
["E 134", "I send you forth", "E"],
["E 135", "Let us turn our faces to the light"],
["E 136", "Let your hearts be ever joyful", "E"],
["E 137", "Lift high the cross"],
["E 138", "Little drops of water"],
["E 139", "Make me a channel of Your peace", "E", "", "", "com"],
["E 140", "Make me a servant"],
["E 141", "Must I go all empty-handed?", "E"],
["E 142", "O blessed house", "E"],
["E 143", "O Master, let me walk with Thee"],
["E 144", "Of service be to Jesus"],
["E 145", "One thing's needful", "E"],
["E 146", "Only remembered", "E"],
["E 147", "Pass it on"],
["E 148", "Rise, my soul, gird thee with power", "E"],
["E 149", "Seek ye first", "E"],
["E 150", "So much to learn remains", "E"],
["E 151", "So send I you"],
["E 152", "Stand up for Jesus"],
["E 153", "Striving onward, pressing forward", "E"],
["E 154", "Take time to be holy", "E"],
["E 155", "Take time to be holy"],
["E 156", "The Servant King"],
["E 157", "The servant song"],
["E 158", "The time of grace redeem today", "E"],
["E 159", "The work is Thine", "E"],
["E 160", "There are lonely hearts to gladden"],
["E 161", "Thy hand, O God, has guided"],
["E 162", "To the work! To the work!"],
["E 163", "To your first love be returning", "E"],
["E 164", "What shall the harvest be", "E"],
["E 165", "While the sun for us shines brightly"],
["E 166", "Who is on the Lord's side?"],
["E 167", "Work, for the night is coming", "E"],
["E 168", "Yield not to temptation", "E"],
["E 169", "You servants of the Lord"],
["E 170", "A little child feels longing for its mother"],
["E 171", "A little ship sailed o'er the sea", "E"],
["E 172", "A mighty fortress is our God"],
["E 173", "And Jesus said"],
["E 174", "Be still, my soul", "E"],
["E 175", "Come , come, ye saints"],
["E 176", "Commit your way, confiding", "E"],
["E 177", "Count your blessings"],
["E 178", "Forever with the Lord"],
["E 179", "God is our stregth and refuge"],
["E 180", "God moves in a mysterious way"],
["E 181", "God of our fathers"],
["E 182", "God will take care of you", "E"],
["E 183", "Hiding in Thee"],
["E 184", "Hold the fort", "E"],
["E 185", "How firm a foundation"],
["E 186", "I know whom I have believed"],
["E 187", "I will guide thee", "E"],
["E 188", "If God Himself is for me", "E"],
["E 189", "I'm the child of a King", "E"],
["E 190", "In times like these"],
["E 191", "It is no secret", "E"],
["E 192", "I've found a joy in sorrow"],
["E 193", "Jesus never fails"],
["E 194", "Jesus, Lover of my soul"],
["E 195", "Jesus, Lover of my soul", "E"],
["E 196", "Jesus, Saviour, pilot me"],
["E 197", "Lead on, O King eternal"],
["E 198", "Light after darknes", "E"],
["E 199", "Lord, Thou camest in compassion", "E"],
["E 200", "Make no plans without the Lord", "E"],
["E 201", "Master, the tempest is raging", "E"],
["E 202", "My Jesus is my dearest Friend", "E"],
["E 203", "Not human advice"],
["E 204", "On eagle's wings"],
["E 205", "On Zion's mount of radiant light", "E", "", "", "bs,com"],
["E 206", "Our God is true", "E"],
["E 207", "Safely faith through life doth guide us", "E"],
["E 208", "Should my pathway lead"],
["E 209", "Someday there will be peace"],
["E 210", "Star, to which I'm looking"],
["E 211", "Strong is my Lord Jesus' hand", "E"],
["E 212", "Take Jesus in your ship of of life", "E"],
["E 213", "Take the name of Jesus with you", "E"],
["E 214", "The King of love Shephers is"],
["E 215", "The Lord knows all His people"],
["E 216", "The Lord's my Shepherd_irvine"],
["E 217", "The Lord's my Shepherd_irvine"],
["E 218", "Through every land they journey"],
["E 219", "Toiling bravely onward"],
["E 220", "Trust and obey"],
["E 221", "Trusting each and every day"],
["E 222", "Victory through grace"],
["E 223", "Wait, my soul, and tarry"],
["E 224", "We are in need of patience"],
["E 225", "We would our saviour see"],
["E 226", "What a Friend we have in Jesus", "E"],
["E 227", "When Jesus lives in me"],
["E 228", "when the storms of life are raging"],
["E 229", "With a golden staff in hand"],
["E 230", "With You, O Lord, united"],
["E 231", "Zion's sheltered by God's mountains"],
["E 232", "Abide with me"],
["E 233", "Abide with us, Lord Jesus"],
["E 234", "As the deer"],
["E 235", "Be Thou my Vision"],
["E 236", "Before my heart's King bowing", "", "", "", "com"],
["E 237", "Blessed Jesus, at Thy word"],
["E 238", "Dear Lord, I give completely", "E", "", "", "com"],
["E 239", "Gentle Shepherd, come and lead us"],
["E 240", "Give me a perfect heart", "", "", "", "com"],
["E 241", "God, all-pow'rful,help the humble"],
["E 242", "Guide me, O Thou great Redeemer"],
["E 243", "Have Thine own way, Lord", "", "", "", "com"],
["E 244", "Here is my heart", "", "", "", "com"],
["E 245", "I need Thee every hour", "E"],
["E 246", "I want to love Thee more sincerely", "", "", "", "com"],
["E 247", "Just as God leads me"],
["E 248", "Lord, preserve my soul"],
["E 249", "Lord, teach us how to pray aright"],
["E 250", "Master, speak, Thy servant heareth", "E"],
["E 251", "My Father, as You will"],
["E 252", "Nearer, my God, to Thee_mason", "", "", "", "com"],
["E 253", "Nearer, my God, to Thee_mason", "", "", "", "com"],
["E 254", "No longer my own"],
["E 255", "O for a heart to praise my God", "", "", "", "com"],
["E 256", "O Love, that will not let me go"],
["E 257", "Prayer is the soul's sincere desire"],
["E 258", "Precious Lord, take my hand"],
["E 259", "Saviour, like a shepherd lead us"],
["E 260", "See, I spread my arms in yearning", "", "", "", "com"],
["E 261", "Sweet hour of prayer", "E"],
["E 262", "Take Thou my hand and lead me"],
["E 263", "Teach me the measure of my days"],
["E 264", "To pray to God in heaven"],
["E 265", "Whate'er my God ordains is right"],
["E 266", "Your way, not mine, O Lord"],
["E 267", "A sparkling stream", "", "", "", "com"],
["E 268", "Arise, your light is come"],
["E 269", "Behold Me standing at your door"],
["E 270", "Bethesda is open", "E"],
["E 271", "Break Thou the Bread of life"],
["E 272", "Christ, whose glory fills the skies"],
["E 273", "Come in, O Lord, come in", "", "", "", "com"],
["E 274", "Come near, you are invited", "", "", "", "com"],
["E 275", "Come to the life-giving fountain", "", "", "", "com"],
["E 276", "Come to the Saviour", "", "", "", "com"],
["E 277", "Come, for the feast is spread", "", "", "", "com"],
["E 278", "For you I am praying", "E"],
["E 279", "Fresh from the throne of glory", "E", "", "", "com"],
["E 280", "Glorious, glorious is the Work of God", "", "", "", "com"],
["E 281", "God is offering through the Saviour"],
["E 282", "Hark Jesus calls"],
["E 283", "Hark the gospel bells are ringing", "", "", "", "", "", "1:6"],
["E 284", "Hark Who's knocking"],
["E 285", "Have you any room for Jesus?"],
["E 286", "Hearken A narrow way"],
["E 287", "I know of a city"],
["E 288", "I know of a fountain"],
["E 289", "I know of a river"],
["E 290", "Jesus is calling"],
["E 291", "Let in your Saviour"],
["E 292", "Let the children to Me gather"],
["E 293", "Let there be light"],
["E 294", "Love divine, all loves excelling", "", "", "", "com"],
["E 295", "O come now to Jesus"],
["E 296", "O come with me"],
["E 297", "O where is Jesus?"],
["E 298", "Of compassion and salvation"],
["E 299", "Open now your gates of beauty"],
["E 300", "Softly and tenderly"],
["E 301", "See, who's standing at your door"],
["E 302", "Shine, Jesus, shine"],
["E 303", "There is a call most precious", "", "", "", "com"],
["E 304", "There is still room"],
["E 305", "There's a place"],
["E 306", "Thou didst leave Thy throne"],
["E 307", "Welcome to the Fount of Mercy", "", "", "", "com"],
["E 308", "Whosoever heareth", "", "", "", "com"],
["E 309", "Why wait ye still outside the portals?", "", "", "", "com"],
["E 310", "Wonderful words of life", "E", "", "", "com"],
["E 311", "Amazing grace", "E", "", "", "com"],
["E 312", "Come, Thou fount of every blessing"],
["E 313", "Endless compassion", "E"],
["E 314", "Forgive our sins as we forgive", "", "", "", "com"],
["E 315", "Fountain of purity", "", "", "", "com"],
["E 316", "Here is Jesus, here is mercy", "", "", "", "com"],
["E 317", "How often do I wonder", "", "", "", "com"],
["E 318", "I hear Thy welcome voice", "", "", "", "com"],
["E 319", "I know of something precious", "", "", "", "com"],
["E 320", "I live by grace and kindness", "", "", "", "com"],
["E 321", "I stood at mercy's gate"],
["E 322", "I want a principle within", "", "", "", "com"],
["E 323", "In Jesus I have found salvation", "", "", "", "com"],
["E 324", "In Your grace"],
["E 325", "I've found a place I love so well", "E", "", "", "com"],
["E 326", "I've found the spring of blessing", "", "", "", "com"],
["E 327", "Jesus paid it all", "", "", "", "com"],
["E 328", "Jesus sinners does receive"],
["E 329", "Jesus, what a friend for sinners", "", "", "", "com"],
["E 330", "Just as I am"],
["E 331", "O boundless Joy, there is salvation!"],
["E 332", "O happy day", "", "", "", "com"],
["E 333", "Pass me not, O gentle Saviour", "E"],
["E 334", "Search me, O God", "", "", "", "com"],
["E 335", "The great Physician", "", "", "", "com"],
["E 336", "There is a fountain"],
["E 337", "There's a wideness in God's mercy"],
["E 338", "This is a day of new beginnings", "", "", "", "com"],
["E 339", "What a sea of grace", "", "", "", "com"],
["E 340", "With contrite heart I come to Thee", "", "", "", "com"],
["E 341", "Grant us, Lord, due preparation", "", "", "", "com"],
["E 342", "Host and king of grace", "", "", "", "com"],
["E 343", "Let us break bread together", "", "", "", "com"],
["E 344", "A river keeps the pastures green"],
["E 345", "Beautiful, glorious moment", "E"],
["E 346", "Blessed is the peace to my heart", "E"],
["E 347", "Come, share the Lord", "E"],
["E 348", "From Jesus' love, the fountain pure"],
["E 349", "How sacred, holy is this place"],
["E 350", "I found a place of peace and rest"],
["E 351", "I will remember Thee"],
["E 352", "I'm reconciled by mercy"],
["E 353", "I'm resting now at Jesus' feet"],
["E 354", "Neath my Saviour's wings abiding"],
["E 355", "O how blessed are the people"],
["E 356", "Purest fount of love is flowing", "E", "", "", "", "", "1:6"],
["E 357", "Redeemed, I am blessed in Jesus_cupido"],
["E 358", "Redeemed, I am blessed in Jesus_cupido"],
["E 359", "Sweetest bread of heaven"],
["E 360", "What joy 'tis redeemed to be", "E"],
["E 361", "With pure delight and bliss o'erflowing"],
["E 362", "A miracle of love"],
["E 363", "A wonderful Saviour is Jesus"],
["E 364", "Behold, O how pleasant"],
["E 365", "Come, everyone, and join our song"],
["E 366", "Dear brothers and dear sisters"],
["E 367", "Hark, my soul"],
["E 368", "Heart with heart in love united"],
["E 369", "Help us to help each other"],
["E 370", "His love"],
["E 371", "How blessed and glorious with Jesus", "E", "", "", "com"],
["E 372", "I fare so well with you"],
["E 373", "I have found a Friend is Jesus", "", "", "", "com"],
["E 374", "I heard the voice of Jesus say"],
["E 375", "I know a heart I call my own", "", "", "", "com"],
["E 376", "I praise God's love in adoration", "E", "", "", "com"],
["E 377", "In Christ there is no east or west"],
["E 378", "In the garden"],
["E 379", "Into pastures green and fair", "E", "", "", "com"],
["E 380", "Jesus loves me", "", "", "Children"],
["E 381", "Jesus, Lord, we look to Thee", "", "", "", "com"],
["E 382", "Jesus, my truest friend", "E"],
["E 383", "Jesus, the very thought of Thee"],
["E 384", "Lord, more would I love Thee", "E"],
["E 385", "O how precious are the moments", "E"],
["E 386", "O love, the golden sunshine bright", "", "", "", "com"],
["E 387", "O Master of the loving heart", "", "", "", "com"],
["E 388", "O the deep, deep love of Jesus"],
["E 389", "On the mount of bliss ascending", "", "", "", "com"],
["E 390", "Our God is loving"],
["E 391", "Peace that God has given", "", "", "", "com"],
["E 392", "Peace, O how precious", "", "", "", "com"],
["E 393", "Seeing I am Jesus' lamb"],
["E 394", "Tell me the stories of Jesus"],
["E 395", "The gift of love"],
["E 396", "The love of God", "", "", "", "", "", "1:6"],
["E 397", "Think about His love"],
["E 398", "To our loving God sing praises"],
["E 399", "We have a gentle shepherd"],
["E 400", "When peace with the Father", "E", "", "", "com"],
["E 401", "When I'm with Him"],
["E 402", "Where charity and love prevail"],
["E 403", "Again He'll come"],
["E 404", "Ascend to Zion's highest", "E"],
["E 405", "Beyond the sunset_Rodriques"],
["E 406", "Come ye that love the Lord", "E"],
["E 407", "Deep river"],
["E 408", "Forth,forth, my heart, to heaven", "E"],
["E 409", "Gathering homeward, you pilgrims", "E", "", "", "", "", "1:6"],
["E 410", "Gird on your Armour", "E"],
["E 411", "Glory for me", "E"],
["E 412", "How will it be?"],
["E 413", "I see in spirit", "E"],
["E 414", "My Lord! What a morning"],
["E 415", "My Saviour first of all"],
["E 416", "No night there", "E"],
["E 417", "O Son of God, we wait for Thee", "E"],
["E 418", "Oh,what a change!"],
["E 419", "Our King doth come"],
["E 420", "Rejoice, all ye believers"],
["E 421", "Safe in the arms of Jesus"],
["E 422", "Sometime we'll understand"],
["E 423", "Steal away"],
["E 424", "The bride has waited, O so long", "E"],
["E 425", "The Bridegroom comes", "E"],
["E 426", "The Bridegroom soon will call us"],
["E 427", "The king shall come"],
["E 428", "The Lord appears when all is still"],
["E 429", "There is a land"],
["E 430", "To Christ, the Lord, be faithfull"],
["E 431", "Wake, arise, for night is flying"],
["E 432", "We are waiting, blessed Saviour"],
["E 433", "We shall see Him as He is"],
["E 434", "When He cometh", "E"],
["E 435", "When strikes the hour?", "E"],
["E 436", "Who overcometh", "N", "", "", "com"],
["E 437", "Beautiful, glorius Zion", "E"],
["E 438", "Beyond the sunset_Rodriques"],
["E 439", "Beyond, where clouds no more appear", "E"],
["E 440", "Depart, dear child"],
["E 441", "For all the saints"],
["E 442", "For my homestead"],
["E 443", "Homeland mine"],
["E 444", "I have a home beyond the river", "E"],
["E 445", "I know a realm where Jesus dwells", "E"],
["E 446", "In God's kingdom I long to be", "E"],
["E 447", "O the home of my soul is on high", "E"],
["E 448", "Our home"],
["E 449", "Shall we meet once more in glory", "E"],
["E 450", "Shall I meet you at the fountain", "E"],
["E 451", "Somewhere beyond the sunset"],
["E 452", "Swing low, sweet chariot", "E"],
["E 453", "Ten thousand times ten thousand", "E"],
["E 454", "Ten thousand times ten thousand"],
["E 455", "The home of the Father", "E"],
["E 456", "The Lord of the harvest beckons"],
["E 457", "There is a glorious land", "E"],
["E 458", "Golden harps are sounding"],
["E 459", "On your ascension, Lord, alone"],
["E 460", "Breathe on me, breath of God", "E"],
["E 461", "Breathe upon us, Holy Spirit", "E"],
["E 462", "Come down, O love divine"],
["E 463", "Come, fgracious Spirti, heavenly Dove"],
["E 464", "Come, O come Thou quickening Spirit"],
["E 465", "Holy Ghost of truth and power"],
["E 466", "Holy Spirit"],
["E 467", "Holy Spirit, come confirm us"],
["E 468", "Holy Spirit, faithful guide", "E"],
["E 469", "Holy Spirit, heal my soul"],
["E 470", "Holy Spirit, Truth divine"],
["E 471", "O come, eternal Spirit"],
["E 472", "O enter, Lord, Thy temple"],
["E 473", "O Holy Spirit, enter in"],
["E 474", "O thou joyful Whitsuntide"],
["E 475", "Pentecostal power"],
["E 476", "Sing praises on this festive day"],
["E 477", "The Comforter has come"],
["E 478", "Another year is dawning"],
["E 479", "Bless us, Lord, this final day"],
["E 480", "Earthly pleasures are but fleeting"],
["E 481", "Jesus, shall our watchword be"],
["E 482", "Now this year, too, hes ended"],
["E 483", "The year so still is ending"],
["E 484", "Today we come anew"],
["E 485", "Glad hosanna! David's Son"],
["E 486", "Hosanna, loud hossana"],
["E 487", "In huble guise He's nearing"],
["E 488", "With glad psalms"],
["E 489", "All , Lord, for Thee", "E", "", "", "com"],
["E 490", "Blest Man of Calvary"],
["E 491", "He gave His life", "E"],
["E 492", "He never said a mumbalin' word"],
["E 493", "I gave My life for thee", "E", "", "", "com"],
["E 494", "Lead me to Calvary"],
["E 495", "My faith looks up to Thee"],
["E 496", "O Lamb of God divine"],
["E 497", "O sacred Head,now wounded"],
["E 498", "Rock of Ages, cleft for me"],
["E 499", "There is a green hill far away"],
["E 500", "The old rugged cross", "E"],
["E 501", "Were you there?"],
["E 502", "when I survey the wondrous cross", "", "", "", "com"],
["E 503", "when I survey the wondrous cross", "", "", "", "com"],
["E 504", "You gave Your precious life", "", "", "", "com"],
["E 505", "Alleluia! Sing to Jesus"],
["E 506", "Alleluia,alleluia! Hearts to haven"],
["E 507", "Blessing and honour"],
["E 508", "Christ the Lord is risen today"],
["E 509", "Christ triumphant, ever reigning"],
["E 510", "Crown him with many crowns"],
["E 511", "Hallelujah! Resurrected"],
["E 512", "I know that my Redeemer lives"],
["E 513", "Jesus Christ is risen today"],
["E 514", "Joy- bells ringing"],
["E 515", "O beautiful Easter"],
["E 516", "Rejoice, He has risen!"],
["E 517", "Rejoice, the Lord is King"],
["E 518", "See, what a morning"],
["E 519", "Sing, all you Christians"],
["E 520", "The day of resurrection"],
["E 521", "We welcome glad Easter"],
["E 522", "Awake,sons of the kingdom"],
["E 523", "Come, Thou long-expected Jesus"],
["E 524", "Comfort now My people"],
["E 525", "Hail to the Lord's annointed"],
["E 526", "Lift up your heads, O mighty gates"],
["E 527", "Lift up your heads, O mighty gates"],
["E 528", "O how shall I receive You?"],
["E 529", "Zion's daughter, O be glad", "E", "", "", "", "c"],
["E 530", "All my heart rejoices", "", "", "", "", "c"],
["E 531", "Angels, from the realms of glory", "E", "", "", "", "c"],
["E 532", "As with gladness men of old", "", "", "", "", "c"],
["E 533", "A way in a manger", "E", "", "", "", "c"],
["E 534", "A way in a manger", "", "", "", "", "c"],
["E 535", "Bright and glorious is the sky", "", "", "", "", "c"],
["E 536", "Christians, awake", "", "", "", "", "c"],
["E 537", "Come, gather, ye children", "E", "", "", "", "c"],
["E 538", "Fairest Lord Jesus", "E", "", "", "", "c"],
["E 539", "From Heaven above to earth I come", "", "", "", "", "c"],
["E 540", "Gentle Mary laid her Child", "E", "", "", "", "c"],
["E 541", "Glorious light", "", "", "", "", "c"],
["E 542", "Go, tell it on the mountain", "E", "", "", "", "c"],
["E 543", "Good Christian Friends, rejoice", "", "", "", "", "c"],
["E 544", "Hark! The herald angels sing", "E", "", "", "", "c"],
["E 545", "In Bethlehem the lowly", "E", "", "", "", "c"],
["E 546", "It came upon the midnight clear", "", "", "", "", "c"],
["E 547", "It came upon the midnight clear", "", "", "", "", "c"],
["E 548", "Joy to the world", "E", "", "", "", "c"],
["E 549", "Lo, how a Rose e'er blooming", "", "", "", "", "c"],
["E 550", "O come, all ye faithful", "E", "", "", "", "c"],
["E 551", "O thou joyful Christmastide", "", "", "", "", "c"],
["E 552", "O little town of Bethlehem", "E", "", "", "", "c"],
["E 553", "O little town of Bethlehem", "", "", "", "", "c"],
["E 554", "O morning Star, how fair and bright", "", "", "", "", "c"],
["E 555", "O thou joyful Christmastide", "", "", "", "", "c"],
["E 556", "O what peace and what rejoicing", "E", "", "", "", "c"],
["E 557", "On Christmas night all Christians sing", "", "", "", "", "c"],
["E 558", "Once in royal David's city", "E", "", "", "", "c"],
["E 559", "Rejoice, O ye mortals", "", "", "", "", "c"],
["E 560", "Silent night, holy night", "E", "", "", "", "c"],
["E 561", "The first Nowell", "E", "", "", "", "c"],
["E 562", "While shepherds watched their flocks", "E", "", "", "", "c"],
["E 563", "Bless this child", "", "", "", "", "c"],
["E 564", "Come as a child", "", "", "", "", "c"],
["E 565", "Dearest Jesus, we are here"],
["E 566", "Gentle shepherd, who His own"],
["E 567", "Jesus, we pray now"],
["E 568", "Lord, we bring to You our children"],
["E 569", "By vows of love together bound"],
["E 570", "Give Your grace upon their way"],
["E 571", "God grant you now His loving blessing"],
["E 572", "Lord, with fervence do we pray"],
["E 573", "O happiness"],
["E 574", "O perfect love"],
["E 575", "Wedding bells are ringing"],
["E 576", "Before the congregation"],
["E 577", "I vow this day, Lord, to be loyal"],
["E 578", "Seek early in life's morning"],
["E 579", "Christ made the sure foundation"],
["E 580", "Christ is our Cornerstone"],
["A 1", "Almagtig is ons God", "E"],
["A 2", "Dankie vir 'n Vriend soos Jy"],
["A 3", "Die Sionslied"],
["A 4", "Eer aan die Vader"],
["A 5", "Ek het Jou lief"],
["A 6", "Ek het U lief"],
["A 7", "Ek prys die almag van my God"],
["A 8", "God is in ons midde", "E"],
["A 9", "God is in ons midde"],
["A 10", "Grote God", "E"],
["A 11", "Halleluja! Ons loof U, Heer"],
["A 12", "Halleluja, skone môre!", "E"],
["A 13", "Heilig, heilig, heilig", "E"],
["A 14", "Hoe groot is U arr Hine", "E"],
["A 15", "Hoe groot is U! arr Isaacs"],
["A 16", "Hoe lieflik op die Sabbatdag", "E"],
["A 17", "Hy is my God"],
["A 18", "In eerbied, Heer"],
["A 19", "Jesus, Jy's wonderbaar", "", "", "", "com"],
["A 20", "My God is mag", "", "", "", "com"],
["A 21", "'n Duisend stemme sing"],
["A 22", "'n Lied van lof en prys"],
["A 23", "'n Vuurtjie steek U aan"],
["A 24", "O glorieryke dag van lig"],
["A 25", "O God wat eeue lank behoed"],
["A 26", "O God, Jy is verhewe"],
["A 27", "So lief het ons die plek"],
["A 28", "U, sal ons eer"],
["A 29", "Waardig aanbidding", "E"],
["A 30", "Ware vreugde gee die Heer", "", "", "", "com"],
["A 31", "Wees stil in die skadu van die Heer", "E"],
["A 32", "Bring lof aan die Vader arr Doane", "E", "", "", "com"],
["A 33", "Bring lof aan die Vader arr Julius", "E", "", "", "com"],
["A 34", "Dank nou die Heer!", "E"],
["A 35", "Ek is vreugdevol"],
["A 36", "Ek prys U, Heer"],
["A 37", "Groot u getrouheid, Heer"],
["A 38", "Grote God, ons loof U, Heer", "E"],
["A 39", "Heer, hoe kan ek Jou genoeg prys"],
["A 40", "Hoe groot is U almagtig goedheid!"],
["A 41", "Jubel, nasies"],
["A 42", "Juig, al wat leef"],
["A 43", "Kom, dank die Heer"],
["A 44", "Kom, volke wat die aard' bewoon"],
["A 45", "Laat ons vrolik sing gesange"],
["A 46", "Loof nou die Here", "E"],
["A 47", "Loof nou die Here arr Stralsund", "E"],
["A 48", "Loof, my siel, die Hemelkoning", "E", "", "", "com"],
["A 49", "Loof, my siel, die Hemelkoning arr Rodriques", "", "", "", "com"],
["A 50", "Majesteit"],
["A 51", "Nou dank ons almal God", "E"],
["A 52", "O, had ek duisend tonge, Here"],
["A 53", "Prys ons Heer met blye lied're"],
["A 54", "Prys tot die Vader"],
["A 55", "Sal ek God nie wil besing nie"],
["A 56", "Sing Hom 'n loflied", "E"],
["A 57", "Vir die aardse skeppingsprag"],
["A 58", "Waarmee, Heer, kan ek U lowe arr Davids", "E"],
["A 59", "Waarmee, Heer, kan ek U lowe arr Bourne"],
["A 60", "Aan die Heilands voete"],
["A 61", "Christus, Heer, wie kan vergeet"],
["A 62", "Daar is 'n naam"],
["A 63", "Die Vaderhuis is ons genot", "E"],
["A 64", "Ek behoort aan U", "", "", "", "com"],
["A 65", "Ek bid nie, Heer, om aardsgewin", "E"],
["A 66", "Ek gee alles oor"],
["A 67", "Ek sal sing van my Verlosser", "E", "", "", "com"],
["A 68", "Ek wil sy naam bely"],
["A 69", "Ek wil U liefhê arr König"],
["A 70", "Ek will U liefhê arr Davids"],
["A 71", "Ek wil vertel"],
["A 72", "Genade vir my"],
["A 73", "Heer, u woord bekoor my lewe"],
["A 74", "Heer, my Heiland en my Herder", "E"],
["A 75", "Heerlik, heerlik bou ons God arr Gohle", "E", "", "", "com"],
["A 76", "Heerlik, heerlik bou ons God arr Davids", "", "", "", "com"],
["A 77", "Hemelwaarts lei onse baan", "E"],
["A 78", "Hy is wonderlik"],
["A 79", "Hy lewe in my"],
["A 80", "Jesus, my Redder arr Cupido", "", "", "", "com"],
["A 81", "Meer heiligheid gun my", "E", "", "", "com"],
["A 82", "My Heiland leef"],
["A 83", "Neem my lewe, God en Heer", "E"],
["A 84", "O grote God"],
["A 85", "Ons wil dit nou verkondig"],
["A 86", "Salig die wete", "E", "", "", "com"],
["A 87", "Siel, ontwaak! Ek wil verkondig", "E", "", "", "com"],
["A 88", "Staan nou op, jul Godsgetuies", "E"],
["A 89", "Wat 'n glorieryke vaandel"],
["A 90", "Aan die werk! Aan die werk!", "E"],
["A 91", "Bewaar sy woord"],
["A 92", "Bly in die lig", "E"],
["A 93", "Dit is u werk, my God en Heer", "E"],
["A 94", "Ek sal strewe na die lewe", "E"],
["A 95", "Gee vir die Heer net jou beste", "E"],
["A 96", "Geseënde huis"],
["A 97", "Glansryk skyn ons Gods genade"],
["A 98", "Laat ons eerder opkyk na die lig"],
["A 99", "Laat ons harte alltyd vrolik"],
["A 100", "Laat, Heer, jou vrede deur my vloei", "E", "", "", "com"],
["A 101", "Ontwaak en laat ons ylings", "E"],
["A 102", "Ontwaak!", "E"],
["A 103", "Staan op vir Jesus", "E"],
["A 104", "Staan vas teen versoeking", "E"],
["A 105", "Steeds in gedagte"],
["A 106", "Wees waaksaam"],
["A 107", "Werk, want die nag kom nader arr Mason", "E"],
["A 108", "Werk, want die nag kom nader arr Hughes"],
["A 109", "Wyl ons nog in jeug se lente"],
["A 110", "Dan is my God altyd daar"],
["A 111", "Dapper voorwaarts strydend", "E"],
["A 112", "Die almag van sy hand"],
["A 113", "Die Heer is so goed vir my"],
["A 114", "Die Heer, my Herder, sorg vir my"],
["A 115", "Die kleine kind verlang"],
["A 116", "Eendag sal daar vrede wees"],
["A 117", "Ek bewaar jou"],
["A 118", "Ek is Koning se kind"],
["A 119", "Geen menslike raad"],
["A 120", "God is getrou!", "E"],
["A 121", "Gods dade is volmaak"],
["A 122", "Grote God, liewe Heer"],
["A 123", "In hierdie tyd"],
["A 124", "In jou tempel"],
["A 125", "Jesus, Redder, lei my weë", "E"],
["A 126", "Jesus, Sielevriend almagtig"],
["A 127", "Lei my weg deur woeste storme"],
["A 128", "Met U, o Heer, verbonde"],
["A 129", "My God, ek wil getrou volhard"],
["A 130", "My Jesus is my beste Vriend", "E"],
["A 131", "'n Vaste burg is onse God", "E"],
["A 132", "Na die oorwinning"],
["A 133", "O hoe soet die naam van Jesus", "E"],
["A 134", "Ons geloof beheer ons lewe"],
["A 135", "Ons het geduld so nodig"],
["A 136", "Op die lewenspad"],
["A 137", "Op reis deur vele lande"],
["A 138", "Ster wat ek bewonder", "E"],
["A 139", "Tel jou gawes", "E"],
["A 140", "U lei my na waters"],
["A 141", "U lei u volk so trou"],
["A 142", "U woord is so kosbaar"],
["A 143", "Van lig-omstraalde Sionsberg", "E"],
["A 144", "Vir ewig by die Heer", "E"],
["A 145", "Volg en vertrou"],
["A 146", "Wag en wees tevrede", "E"],
["A 147", "Wat 'n Vriend het ons in Jesus", "E"],
["A 148", "Bly by my, Heer", "E"],
["A 149", "By U, Jesus, vind ek vrede"],
["A 150", "Elk' uur, ja elke stond'"],
["A 151", "Gee my 'n reine hart"],
["A 152", "Heer, bewaar my siel"],
["A 153", "Heer, neem dan nou my hande"],
["A 154", "Heiland, soos 'n Herder lei ons"],
["A 155", "Hier knielend voor my Koning", "", "", "", "com"],
["A 156", "Ken my, o Heer", "", "", "", "com"],
["A 157", "My hart, o Heer, is in u hande"],
["A 158", "Nader, my God, tot U", "E"],
["A 159", "Neem my hand, liewe Heer", "E"],
["A 160", "O Heer, geheel gegewe", "", "", "", "com"],
["A 161", "Soos God my lei", "E"],
["A 162", "Soos 'n hert"],
["A 163", "Soos U dit wil, Heer!", "", "", "", "com"],
["A 164", "Wees my Gids, o groot Verlosser", "E"],
["A 165", "Betesda staan ope", "E"],
["A 166", "Daar is 'n roep so kosbaar", "E", "", "", "com"],
["A 167", "Daar is 'n roep so kosbaar arr Tromp", "", "", "", "com"],
["A 168", "Daar vloei 'n stroom arr Gohle", "E", "", "", "com"],
["A 169", "Daar vloei 'n stroom arr Vollweiler", "", "", "", "com"],
["A 170", "Ek weet van 'n stad"],
["A 171", "God bied nou nog deur die Heiland"],
["A 172", "Hoor Jesus roep", "E"],
["A 173", "Iedereen wat luister", "E", "", "", "com"],
["A 174", "Jesus straal in glorie, prag"],
["A 175", "Kom na die bron van die lewe", "E", "", "", "com"],
["A 176", "Kom na die fees so groot", "", "", "", "com"],
["A 177", "Kom saam met my"],
["A 178", "O siel, kom na die Heer", "", "", "", "com"],
["A 179", "O kom nou na Jesus arr Main"],
["A 180", "O kom nou na Jesus arr Bailey"],
["A 181", "Saggies en inniglik arr Thompson"],
["A 182", "Saggies en inniglik arr Davids"],
["A 183", "Soet kom die roep", "", "", "", "com"],
["A 184", "Vars van die troon van glorie", "E", "", "", "com"],
["A 185", "Waar vind ek Jesus?", "E"],
["A 186", "Woorde wat lewe bring", "E", "", "", "com"],
["A 187", "Aan die kruis, Heer, het U gely", "", "", "", "com"],
["A 188", "Daar is 'n bron", "E", "", "", "com"],
["A 189", "Diepe bepeinsing", "", "", "", "com"],
["A 190", "Ek hoor sy liefdesroep", "E", "", "", "com"],
["A 191", "Ek kom deemoedig tot U, Heer", "E", "", "", "com"],
["A 192", "Ek lewe van barmhartigheid", "E", "", "", "com"],
["A 193", "Ek weet van niks soe lieflik", "E", "", "", "com"],
["A 194", "Ek word bevry", "", "", "", "com"],
["A 195", "Gaan my nie verby, o Heiland", "E"],
["A 196", "Genade groot", "E", "", "", "com"],
["A 197", "Genade groot", "", "", "", "com"],
["A 198", "Genade smag ek, Heer", "E"],
["A 199", "Hy is my Leidsman"],
["A 200", "In Jesus het ek heil gevonde", "E", "", "", "com"],
["A 201", "Jesus, my Redder", "", "", "", "com"],
["A 202", "Jesus, wat 'n vriend vir sondaars", "E", "", "", "com"],
["A 203", "n Bron van seën gevonde", "E", "", "", "com"],
["A 204", "n Genadestroom", "E", "", "", "com"],
["A 205", "O Blye dag", "", "", "", "com"],
["A 206", "O welke vreugde bring verlossing", "E"],
["A 207", "U is vir my so innig goed", "", "", "", "com"],
["A 208", "Ek jubel luid in louter vreugde"],
["A 209", "Genade bring versoening"],
["A 210", "Heerlike, lieflike stonde"],
["A 211", "Kom,deel die Heer"],
["A 212", "O, hoe salig is die siele"],
["A 213", "Ryke koning vol genade"],
["A 214", "U bring my verlossing, Heer", "E"],
["A 215", "Verlos is ek, salig in Jesus", "E"],
["A 216", "Welke reine stroom van liefde"],
["A 217", "As vrede, so kosbaar", "", "", "", "com"],
["A 218", "By Hom te wees"],
["A 219", "Die liefde Gods"],
["A 220", "Ek ken 'n hart, 'n heilig een", "", "", "", "com"],
["A 221", "Ek wil graag soos Jesus liefhê"],
["A 222", "God is die liefde"],
["A 223", "God is liefde", "", "", "", "com"],
["A 224", "Hart met hart in een verbonde"],
["A 225", "Het jy My lief"],
["A 226", "Hoe heerlike,hoe salig met Jesus", "E", "", "", "com"],
["A 227", "Ja, 'n Vriend het ek gevonde arr Isaacs"],
["A 228", "Ja, 'n Vriend het ek gevonde arr Isaacs"],
["A 229", "Kom,almal, sing nou juigend saam"],
["A 230", "Meer wil ek U bemin", "", "", "", "com"],
["A 231", "O liefde, goue sonneskyn", "", "", "", "com"],
["A 232", "O Meester van 'n liefdeshart"],
["A 233", "O, hoe kosbaar is die stonde", "E"],
["A 234", "O Meester van 'n liefdeshart"],
["A 235", "Oor die weiveld groen en geil", "E", "", "", "com"],
["A 236", "Praat ek mense-, eng'letale", "", "", "Kids"],
["A 237", "Salige vrede", "", "", "", "com"],
["A 238", "So innig, innig is Jesusliefde"],
["A 239", "Stil in die gees"],
["A 240", "U bid ek aan, o mag van liefde"],
["A 241", "Bly Christus hier getrou steeds"],
["A 242", "Die Heiland kom"],
["A 243", "Ek het van verre"],
["A 244", "Ek lewe vir die dag"],
["A 245", "Glorie vir my"],
["A 246", "Hy wat oorwin"],
["A 247", "Ja, eens sal ons verstaan"],
["A 248", "Jerusalem"],
["A 249", "Kom jul wat Hom bemin"],
["A 250", "Nooit nag daar"],
["A 251", "O Jerusalem, Godstuiste"],
["A 252", "Omgord die lendene, bereid"],
["A 253", "Ons is waaksaam op U wagtend"],
["A 254", "Ons sal ons Heer aanskou"],
["A 255", "U bruid wag reeds so lank op U"],
["A 256", "Veilig in Jesus arme"],
["A 257", "Verheug tesaam, getroues"],
["A 258", "Voort, voort, my hart na hemel"],
["A 259", "Voorwaar, Hy sal verskyn"],
["A 260", "Daar is 'n glorieland"],
["A 261", "Die huis van die Vader"],
["A 262", "Ek ken 'n ryk waar Jesus woon"],
["A 263", "Heerlike, lieflike Sion"],
["A 264", "In ewigheid"],
["A 265", "In Gods heerlikheid wil ek woon"],
["A 266", "Kry ek jou by die fonteine?"],
["A 267", "Maar dié vertroosting bly"],
["A 268", "Na my tuiste"],
["A 269", "O my tuiste is daar by die Heer"],
["A 270", "Waar nooit meer wolke hoog oprys"],
["A 271", "Kom tot ons, o Gees van lewe"],
["A 272", "O God, o Gees van lig en lewe"],
["A 273", "O Kom, U Gees van waarheid"],
["A 274", "Tree U my hart nou binne"],
["A 275", "Die jaar loop stil ten einde"],
["A 276", "Die jaar snel nou ten einde"],
["A 277", "Jesus sal ons wagwoord wees"],
["A 278", "Vandag plaas ons opnuut"],
["A 279", "Geklee in skaam'le klere"],
["A 280", "Sing jou Koning psalms"],
["A 281", "Sing hosanna! Dawids Seun"],
["A 282", "Aanskou die Heiland, sien die kruis", "", "", "", "com"],
["A 283", "Alles, Heer, vir U", "", "", "", "com"],
["A 284", "Hoor die stem van ewig liefde"],
["A 285", "O Hoof deur mens geskonde"],
["A 286", "O Lam van God, geseën"],
["A 287", "Op 'n heuwel daar ver"],
["A 288", "Vir jou het ek gesterf", "", "", "", "com"],
["A 289", "Ek weet dat my Verlosser leef!"],
["A 290", "Halleluja!"],
["A 291", "Jesus Christus leef"],
["A 292", "Viktoria, my Jesus leef!"],
["A 293", "Blye tyding", "", "", "", "", "c"],
["A 294", "Daar ver in 'n krippie", "E", "", "", "", "c"],
["A 295", "Die Heiland is gebore", "E", "", "", "", "c"],
["A 296", "Dit is weer Kersfees", "", "", "", "", "c"],
["A 297", "Dit kom so sag teen middernag", "E", "", "", "", "c"],
["A 298", "Eng'le van die glorieryke", "E", "", "", "", "c"],
["A 299", "Hoor! Die engelskare sing", "E", "", "", "", "c"],
["A 300", "In Betlehem gebore", "E", "", "", "", "c"],
["A 301", "Kom, alle getroues", "E", "", "", "", "c"],
["A 302", "'n Rosie spruit ontluikend", "E", "", "", "", "c"],
["A 303", "O vreugdevolle Kersfeestyd", "", "", "", "", "c"],
["A 304", "O, die vrolike Kerfeestyd!", "E", "", "", "", "c"],
["A 305", "Skoonste Heer Jesus", "E", "", "", "", "c"],
["A 306", "Stille nag, heilige nag", "E", "", "", "", "c"],
["A 307", "Stralende lig", "", "", "", "", "c"],
["A 308", "Vreugde op aard", "E", "", "", "", "c"],
["A 309", "Welke vreugde, welke vrede", "E", "", "", "", "c"],
["A 310", "Liefste Jesus, ons is hier"],
["A 311", "Heer, o neem ons bede aan"],
["A 312", "Mag God jul albei seën"],
["A 313", "O groot geluk"],
["A 314", "Aan U wil ek, Heer, trou belowe"],
["A 315", "Vandag voor die gemeente"]
];
